# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: 弾性体力学入門
author: #Takuto Maeda
logo: # logo.png
copyright: '2021 Takuto Maeda. All Rights Reserved'

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: 'off'

# Define the name of the latex output file for PDF builds
# latex:
#  latex_documents:
#    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - refs.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/tktmyd/intro-elasticity  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
#  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: false
  use_repository_button: false

sphinx:
  config:
    myst_update_mathjax: False
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

parse:
  myst_enable_extensions:
    - dollarmath
    - amsmath
    - html_image
    - colon_fence